name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8

      - name: Lint (flake8)
        run: |
          flake8 . --max-line-length=120 --extend-exclude .venv,venv,.git,__pycache__

      - name: Import check
        run: |
          python -m compileall -q .
          python -c "import core.esp32_led; import app.web"

